-- Equivalente à migration EF Core 20250923211801_INS_REGISTROS.
-- CURRENT_TIMESTAMP funciona em SQLite e PostgreSQL (GETDATE() é só do SQL Server).
INSERT INTO TABELATESTE (ID, DESCRICAO, DATAHORA) VALUES (1, 'Registro1', CURRENT_TIMESTAMP);
INSERT INTO TABELATESTE (ID, DESCRICAO, DATAHORA) VALUES (2, 'Registro2', CURRENT_TIMESTAMP);
INSERT INTO TABELATESTE (ID, DESCRICAO, DATAHORA) VALUES (3, 'Registro3', CURRENT_TIMESTAMP);
